# Generated by Django 3.0.8 on 2020-07-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('describe', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestManagement.APIProject')),
            ],
        ),
    ]
